services:
  route_optimizer:
    container_name: route_optimizer
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route_optimizer.rule=Host(`travel.like`)"
      - "traefik.http.routers.route_optimizer.entrypoints=web"
      - "traefik.http.services.route_optimizer.loadbalancer.server.port=8501"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
